### PR TITLE
Implemented filtering of fields.

### PR DESCRIPTION
**Pull request by imetallica**

### CODE REVIEW

**Comment by imetallica** [comment]
@slashdotdash I've done a small implementation as you proposed. By default it will filter `password`, `password_confirmation` and `secret`.

**Comment by imetallica** [comment]
Should fix #2.

**Comment by slashdotdash** [comment]
Great, thank you @imetallica.

**Comment by imetallica** [comment]
@slashdotdash if you can push to hex a new version would be great. 😄

**Comment by slashdotdash** [comment]
@imetallica  Sure, it's published to Hex as [v0.3.0](https://hex.pm/packages/commanded_audit_middleware/0.3.0).

**Pull request merged**
